<?php

/**
 * @file
 * <%= moduleName %>_views.module
 */

/**
 * Implements hook_views_api().
 */
function <%= moduleName %>_views_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_menu().
 */
function <%= moduleName %>_views_menu() {
  $items['<%= moduleName %>/views/ajax'] = array(
    'title' => '<%= moduleProper %>',
    'page callback' => '<%= moduleName %>_views_ajax',
    'delivery callback' => 'drupal_json_output',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function <%= moduleName %>_views_theme($existing, $type, $theme, $path) {
  $items['<%= moduleName %>_views_pager'] = array(
    'file' => 'theme/<%= moduleName %>_views.theme.inc',
    'variables' => array('tags' => array(), 'element' => 0, 'parameters' => array(), 'options' => array()),
    'pattern' => '<%= moduleName %>_views_pager__',
  );

  return $items;
}
