<?php

/**
 * @file
 * <%= moduleName %>_views.module
 */

/**
 * Implements hook_views_api().
 */
function <%= moduleName %>_views_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_menu().
 */
function <%= moduleName %>_views_menu() {
  $items['<%= moduleName %>/views/ajax'] = array(
    'title' => '<%= moduleProper %>',
    'page callback' => '<%= moduleName %>_views_ajax',
    'delivery callback' => 'drupal_json_output',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function <%= moduleName %>_views_theme($existing, $type, $theme, $path) {
  $items['<%= moduleName %>_views_pager'] = array(
    'file' => 'theme/<%= moduleName %>_views.theme.inc',
    'variables' => array('tags' => array(), 'element' => 0, 'parameters' => array(), 'options' => array()),
    'pattern' => '<%= moduleName %>_views_pager__',
  );

  return $items;
}

//@todo do we need this?
/**
 * Menu callback, load next row (slide) by ajax.
 */
// function <%= moduleName %>_views_ajax() {
//   $name = $_REQUEST['view_name'];
//   $display_id = $_REQUEST['view_display_id'];
//   $page = isset($_REQUEST['page']) ? $_REQUEST['page'] : 1;

//   $view = views_get_view($name);
//   $view->set_display($display_id);
//   $view->set_current_page($page);
//   $view->pre_execute();
//   $view->execute();
//   $view->preview();

//   $rows = array();
//   foreach ($view->result as $index => $row) {
//     $renderer = $view->style_plugin->row_plugin;

//     // Render view row with item-{number} wrapper.
//     $rows[$view->row_index] = '<div class="item-' . $page . '">' . $renderer->render($row) . '</div>';
//   }

//   if ($rows) {
//     drupal_json_output($rows);
//   }
// }
